auto: true
server: true
permalink: none
baseurl: "http://localhost:4000/"
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/: |
      published: false
      layout: article
      title: Título de tu post 
      abstract: Resument corto del post
      author_twitter: msanchezmora
      author: Magda Sánchez
      categories:
      - articles